#!/bin/bash
# Remove duplicate and large games from nate-games
cd /workspaces/Games/nate-games/0/g

# List of games to remove
GAMES_TO_REMOVE=(
    "fnaf-2"
    "fnaf-3"
    "fnaf-4"
    "fnaf-5"
    "fnaf-fp"
    "fnaf-webgl"
    "fnaf-2hacks"
    "fnaf-3scratch"
    "fnafweb"
    "fnfmobile"
    "fnfneo"
    "fnfvsimposter"
    "fnfmidfight"
    "minecraft-webgl"
    "PrecisionClient"
    "eaglercraft"
    "Paper Minecraft"
    "minecraft-classic"
    "mchacks"
    "geodashmeltdown"
    "geodashscratch"
    "geodashsubzero"
    "geodashworld"
    "slope-2"
    "tunnel-rush2"
    "whg2"
    "whg3"
    "ovo2"
    "ovo3"
    "paperio3d"
    "hole.io-scratch"
    "BloonsTD2"
    "BloonsTD3"
    "BloonsTD4"
    "BloonsTD5"
    "btd-battles"
    "btd-battles2"
    "2048-multitask"
    "run2"
    "run3"
    "slitherscratch"
    "flappybird"
    "gravitydriver"
    "alienhominid"
    "aquapark-slides"
    "helixjump"
    "elasticman"
    "circle"
    "n-gon"
    "greybox"
    "baldisbasics"
    "backrooms"
    "omnomrun"
    "cut-the-rope"
    "bitlife"
    "monkeymart"
    "adarkroom"
    "snowball.io"
    "smashkarts"
    "draw-the-hill"
    "Undertale"
    "Terraria"
    "happyglass"
    "candycrush"
    "tombmask"
    "granny"
    "happywheels"
    "mr-bullet"
    "burger-frights"
    "msic"
    "Fortnite"
    "HexGL"
    "Hextris"
    "giag"
    "bf3d"
    "particleclicker"
    "fruit-ninja"
    "motox3m"
    "couch2048"
    "madgunz"
    "valorant"
    "doodle-jump"
    "shellshockers"
    "krunker"
    "among-us"
    "drive-mad"
    "eggycar"
    "nsmb"
    "smb"
    "sm64"
    "retrobowl"
    "fallguys"
    "Stumble Guys"
    "zombs-royale"
    "gettingoverit"
    "Roblox"
    "Roblox-Offline"
    "stickmanhook"
    "just-fall"
    "1v1lol"
    "HexGL"
    "slitherio"
    "sonic"
)

count=0
for game in "${GAMES_TO_REMOVE[@]}"; do
    if [ -d "$game" ]; then
        rm -rf "$game"
        echo "✓ Removed: $game"
        ((count++))
    else
        echo "- Not found: $game"
    fi
done

echo ""
echo "Total removed: $count games/folders"
echo ""
echo "Calculating final size..."
du -sh /workspaces/Games
